# Generated by Django 3.2.3 on 2021-08-28 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('coral_genus', models.CharField(max_length=255)),
                ('coral_family', models.CharField(max_length=255)),
                ('discoverer', models.CharField(max_length=255)),
                ('year_discovered', models.IntegerField()),
                ('characteristic', models.CharField(max_length=1024)),
                ('kind_of_look_alike', models.CharField(max_length=1024)),
                ('distribution', models.CharField(max_length=1024)),
                ('image_path', models.CharField(max_length=255)),
                ('coral_type', models.CharField(max_length=255)),
                ('full_name_abbreviation', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('messages', models.CharField(max_length=500)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
