# Generated by Django 3.2.3 on 2021-08-28 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='date',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
